name: treasure
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.2

# Add regular dependencies here.
dependencies:
  bloc: ^9.1.0
  path: ^1.9.0
  radartui:
    path: "../radartui"
    # git:
    #   url: https://github.com/dev-hann/radartui

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
